export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('reviews').del()

  // Inserts seed entries
  await knex('reviews').insert([
    {
      id: 1,
      user_id: 3,
      product_id: 4,
      rating: 5,
      title: 'Lane',
      description: 'I love my birb!',
    },
    {
      id: 2,
      user_id: 2,
      product_id: 4,
      rating: 4,
      title: 'Ericsson',
      description: 'Birb could be better....',
    },
    {
      id: 3,
      user_id: 1,
      product_id: 4,
      rating: 5,
      title: 'DarkWard',
      description: 'Birb is majestic. 10/10.',
    },
    {
      id: 4,
      user_id: 4,
      product_id: 4,
      rating: 3,
      title: 'NovaSky',
      description: 'Feathers were a bit flat, but still cuddly.',
    },
    {
      id: 5,
      user_id: 5,
      product_id: 4,
      rating: 4,
      title: 'PixelCraze',
      description: 'Aesthetic is on point. Feels nice too.',
    },
    {
      id: 6,
      user_id: 6,
      product_id: 4,
      rating: 5,
      title: 'TechieTom',
      description: 'Great emotional support plush!',
    },
    {
      id: 7,
      user_id: 7,
      product_id: 4,
      rating: 2,
      title: 'JazzHands',
      description: 'Expected more jazz in the birb.',
    },
    {
      id: 8,
      user_id: 8,
      product_id: 4,
      rating: 4,
      title: 'SunsetRider',
      description: 'Perfect companion for sunsets.',
    },
    {
      id: 9,
      user_id: 9,
      product_id: 4,
      rating: 5,
      title: 'CodeWizard',
      description: 'Casts a charm spell on me every night.',
    },
    {
      id: 10,
      user_id: 1,
      product_id: 3,
      rating: 5,
      title: 'DarkWard',
      description:
        'I didn’t know I needed this until I had it. Cage dreams every night.',
    },
    {
      id: 11,
      user_id: 2,
      product_id: 3,
      rating: 3,
      title: 'ericsson',
      description: 'A bit uncanny but strangely comforting.',
    },
    {
      id: 12,
      user_id: 3,
      product_id: 3,
      rating: 4,
      title: 'Lane',
      description: 'Why is his face so soft? Not complaining.',
    },
    {
      id: 13,
      user_id: 4,
      product_id: 3,
      rating: 2,
      title: 'NovaSky',
      description: 'Can’t sleep when he’s watching me...',
    },
    {
      id: 14,
      user_id: 5,
      product_id: 3,
      rating: 5,
      title: 'PixelCraze',
      description: 'Peak meme decor. Guests love it.',
    },
    {
      id: 15,
      user_id: 6,
      product_id: 3,
      rating: 4,
      title: 'TechieTom',
      description: '10/10 conversation starter during Zoom calls.',
    },
    {
      id: 16,
      user_id: 7,
      product_id: 3,
      rating: 3,
      title: 'JazzHands',
      description: 'Wish it played jazz when you hug it.',
    },
    {
      id: 17,
      user_id: 8,
      product_id: 3,
      rating: 5,
      title: 'SunsetRider',
      description: 'Perfect for long drives and naps. Cage-approved.',
    },
    {
      id: 18,
      user_id: 13,
      product_id: 2,
      rating: 5,
      title: 'ChocoLatte',
      description: 'Typing on this is smoother than my morning coffee.',
    },
    {
      id: 19,
      user_id: 14,
      product_id: 2,
      rating: 4,
      title: 'SonicBoom',
      description: 'Clickity clackity, productivity goes zoom.',
    },
    {
      id: 20,
      user_id: 15,
      product_id: 2,
      rating: 5,
      title: 'NightHawk',
      description: 'Quiet but deadly — just how I like my typing.',
    },
    {
      id: 21,
      user_id: 1,
      product_id: 2,
      rating: 3,
      title: 'DarkWard',
      description: 'Nice build, but the RGB is a bit much for me.',
    },
    {
      id: 22,
      user_id: 2,
      product_id: 2,
      rating: 5,
      title: 'ericsson',
      description: 'Perfect for both code and gaming. Highly recommend.',
    },
    {
      id: 23,
      user_id: 3,
      product_id: 2,
      rating: 4,
      title: 'Lane',
      description: 'Solid keyboard. Keycaps feel great. Would buy again.',
    },
    {
      id: 24,
      user_id: 4,
      product_id: 2,
      rating: 2,
      title: 'NovaSky',
      description: 'Too loud for my office setup. Returned it.',
    },
    {
      id: 25,
      user_id: 5,
      product_id: 2,
      rating: 5,
      title: 'PixelCraze',
      description: 'A mechanical masterpiece. RGB game strong.',
    },
    {
      id: 26,
      user_id: 6,
      product_id: 1,
      rating: 5,
      title: 'TechieTom',
      description: 'Snappy, precise, and affordable. Love it for FPS games.',
    },
    {
      id: 27,
      user_id: 7,
      product_id: 1,
      rating: 4,
      title: 'JazzHands',
      description: 'Great performance, but the RGB doesn’t groove enough.',
    },
    {
      id: 28,
      user_id: 8,
      product_id: 1,
      rating: 5,
      title: 'SunsetRider',
      description: 'Smooth glide and sharp clicks. Perfect on-the-go mouse.',
    },
    {
      id: 29,
      user_id: 9,
      product_id: 1,
      rating: 3,
      title: 'CodeWizard',
      description: 'Works well but lacks some macros I need.',
    },
    {
      id: 30,
      user_id: 10,
      product_id: 1,
      rating: 5,
      title: 'GamerGirl99',
      description: 'Best budget gaming mouse hands down. RGB is a plus!',
    },
    {
      id: 31,
      user_id: 11,
      product_id: 5,
      rating: 5,
      title: 'MrRobot',
      description: 'Smells like justice. Cleans like a revolution.',
    },
    {
      id: 32,
      user_id: 12,
      product_id: 5,
      rating: 4,
      title: 'BetaTester',
      description:
        'Tested on everything from tiles to counters. Passes with flying scents.',
    },
    {
      id: 33,
      user_id: 13,
      product_id: 5,
      rating: 5,
      title: 'ChocoLatte',
      description: 'Smells nostalgic. Like grandma’s house on cleaning day.',
    },
    {
      id: 34,
      user_id: 14,
      product_id: 5,
      rating: 4,
      title: 'SonicBoom',
      description: 'Cleans fast, smells faster. Zooms through grease.',
    },
    {
      id: 35,
      user_id: 15,
      product_id: 5,
      rating: 5,
      title: 'NightHawk',
      description: 'Quietly destroys dirt. A stealthy cleaning beast.',
    },
    {
      id: 36,
      user_id: 1,
      product_id: 5,
      rating: 4,
      title: 'DarkWard',
      description: 'Powerful cleaner, but wish it had a twist cap.',
    },
    {
      id: 37,
      user_id: 2,
      product_id: 5,
      rating: 3,
      title: 'ericsson',
      description: 'Works well, but scent is a bit strong for my taste.',
    },
    {
      id: 38,
      user_id: 3,
      product_id: 5,
      rating: 5,
      title: 'Lane',
      description: 'Smells like victory. Floors shine like new.',
    },
    {
      id: 39,
      user_id: 4,
      product_id: 5,
      rating: 4,
      title: 'NovaSky',
      description: 'Excellent on windows and surfaces. Cloudy mirrors no more.',
    },
    {
      id: 40,
      user_id: 5,
      product_id: 5,
      rating: 5,
      title: 'PixelCraze',
      description: 'My kitchen smells like a digital forest. I dig it.',
    },
    {
      id: 41,
      user_id: 6,
      product_id: 5,
      rating: 5,
      title: 'TechieTom',
      description: 'Used it to clean my PC desk. Feels fresh and germ-free.',
    },
    {
      id: 42,
      user_id: 7,
      product_id: 5,
      rating: 3,
      title: 'JazzHands',
      description:
        'Gets the job done, but scent doesn’t really “swing” for me.',
    },
    {
      id: 43,
      user_id: 8,
      product_id: 5,
      rating: 4,
      title: 'SunsetRider',
      description:
        'Pine breeze on a Sunday clean. Could be stronger on grease.',
    },
    {
      id: 44,
      user_id: 9,
      product_id: 5,
      rating: 5,
      title: 'CodeWizard',
      description: 'It’s like casting a “cleanse” spell. Great product.',
    },
  ])
}
